### ISSUE TITLE
导入数据库报错

### ISSUE THREAD

**Issue by 2213500360** [dinglinfang/suedTirolOpenDataOBDA#1]
ERROR: 错误:  语法错误 在 "1" 或附近的
LINE 323: 1 8201 756877.084000000031665 757877.084000000031665 5169330...
          ^

SQL state: 42601
Character: 7822

我似乎无法导入sql文件后面的数据，请问如何解决？

**Comment by ghxiao** [comment]
你好，

请问你是怎么导入数据库的？PostgreSQL + PostGIS的版本？

**Comment by 2213500360** [comment]
谢谢回复，第一次用PostgreSQL数据库和PostGIS，不太熟悉，现在已经导入数据库成功了。
